apiVersion: apps/v1
kind: Deployment
metadata:
  name: oklah-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oklah-api
  template:
    metadata:
      labels:
        app: oklah-api
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: api
          image: ghcr.io/s0en/oklah-api:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
