apiVersion: v1
kind: Service
metadata:
  name: oklah-api
  labels:
    app: oklah-api
spec:
  selector:
    app: oklah-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
